### ISSUE TITLE
Multi-tenancy release checklist

### ISSUE THREAD

**Issue by paolodamico** [PostHog/whereintheworld#14]
We want any company to be able to use our WITW Cloud version. This is the checklist of what we need:

- [ ] Implement domain whitelist for users so new team members can sign up to their existing team account.
- [ ] Team account signup if user does not match whitelisted domain (only G-Suite workspaces will be supported for now, no GMail accounts, we can support invites later).
- [ ] Ability to remove team members and delete their accounts.
- [ ] Implement Group Analytics with PostHog.
- [ ] Stripe billing?
- [ ] Get some beta teams to try it out. Maybe @timgl has some ideas.
